### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by alishkaahmadov** [SerNet/verinice-veo#1]
Hi everyone, currently I'm facing with cors trouble. When I request from my client-side to this rest api it gives me error below:
"Access to fetch at 'http://mydomain/units' from origin 'http://mydomain' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Can someone help?

**Comment by Agh42** [comment]
Are you tring to run as a container or via the bootRun target? In any case you should be able to set the necessary configuration using environment variables or via an `application.properties` file.
The README.md has some examples. You will find the full list of available variables in the `application.yaml` i.e. for your current problem:

```
veo:
  cors:
    # A comma-separated list of allowed CORS origin-patterns.
    # Example: https://*.domain1.com, https://*.domain1.com:[8080,8081], https://*.domain1.com:[*]
    origins: https://veo-web.verinice.example
```
